const fs = require('fs');
const file = 'src/components/LiveDashboard.tsx';
const lines = fs.readFileSync(file, 'utf8').split('\n');

// ── Patch 3 (bottom first): waveform section
// 1-indexed 1114~1231, 0-indexed 1113~1230, 118 lines
const wave = [
`            {/* 파형 그래프 */}`,
`            <div className="mt-0.5">`,
`              <div className="flex relative">`,
`                <div className="flex flex-col justify-between text-[9px] text-white/20 pointer-events-none"`,
`                  style={{width:'22px',flexShrink:0,height:'56px'}}>`,
`                  <span>100</span><span>50</span><span>0</span>`,
`                </div>`,
`                <div`,
`                  className="relative flex-1 cursor-crosshair"`,
`                  style={{ height:'56px' }}`,
`                  onMouseMove={e => {`,
`                    const r = e.currentTarget.getBoundingClientRect()`,
`                    setGraphPos(Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)))`,
`                  }}`,
`                  onMouseLeave={() => setGraphPos(null)}`,
`                >`,
`                  <svg width="100%" height="56" viewBox="0 0 800 56" preserveAspectRatio="none">`,
`                    <defs>`,
`                      <linearGradient id="wgLive" x1="0" y1="0" x2="0" y2="1">`,
`                        <stop offset="0%" stopColor="#7c3aed" stopOpacity=".45"/>`,
`                        <stop offset="100%" stopColor="#7c3aed" stopOpacity=".03"/>`,
`                      </linearGradient>`,
`                      <clipPath id="liveWaveClip">`,
`                        <rect x="0" y="0" width={liveDotX} height="56"/>`,
`                      </clipPath>`,
`                    </defs>`,
`                    {[0.33, 0.66].map(f => (`,
`                      <line key={f} x1="0" y1={56*f} x2="800" y2={56*f} stroke="rgba(255,255,255,.05)" strokeWidth="1"/>`,
`                    ))}`,
`                    {hClip && (`,
`                      <g>`,
`                        <rect x={hClip.pos/100*800 - 32} y={0} width={64} height={56} fill="rgba(168,85,247,0.15)" rx={3}/>`,
`                        <line x1={hClip.pos/100*800} y1={0} x2={hClip.pos/100*800} y2={56}`,
`                          stroke="#a855f7" strokeWidth={1.5} strokeDasharray="4 3" opacity={0.75}/>`,
`                      </g>`,
`                    )}`,
`                    <path d={buildPath(WAVE,800,56,true)}  fill="url(#wgLive)"  clipPath="url(#liveWaveClip)"/>`,
`                    <path d={buildPath(WAVE,800,56,false)} fill="none" stroke="#7c3aed" strokeWidth="1.5" clipPath="url(#liveWaveClip)"/>`,
`                    {graphPos !== null && (`,
`                      <g>`,
`                        <line x1={graphPos*800} y1={0} x2={graphPos*800} y2={56}`,
`                          stroke="rgba(255,255,255,0.22)" strokeWidth={1} strokeDasharray="3 2"/>`,
`                        <circle cx={graphPos*800} cy={56 - WAVE[waveIdx]*56*0.88}`,
`                          r={3.5} fill="#06b6d4" style={{ filter:'drop-shadow(0 0 5px #06b6d4)' }}/>`,
`                      </g>`,
`                    )}`,
`                    {!animDone ? (`,
`                      <g>`,
`                        <circle cx={liveDotX} cy={liveDotY} r="4" fill="rgba(124,58,237,0.35)">`,
`                          <animate attributeName="r" values="4;14;4" dur="1.2s" repeatCount="indefinite"/>`,
`                          <animate attributeName="opacity" values="0.6;0;0.6" dur="1.2s" repeatCount="indefinite"/>`,
`                        </circle>`,
`                        <circle cx={liveDotX} cy={liveDotY} r="4.5" fill="#7c3aed"`,
`                          style={{ filter:'drop-shadow(0 0 8px rgba(124,58,237,1))' }}/>`,
`                      </g>`,
`                    ) : (`,
`                      <g>`,
`                        <circle cx={liveDotX} cy={liveDotY} r="5" fill="rgba(168,85,247,0.2)">`,
`                          <animate attributeName="r" values="5;18;5" dur="2s" repeatCount="indefinite"/>`,
`                          <animate attributeName="opacity" values="0.5;0;0.5" dur="2s" repeatCount="indefinite"/>`,
`                        </circle>`,
`                        <circle cx={liveDotX} cy={liveDotY} r="4" fill="#a855f7"`,
`                          style={{ filter:'drop-shadow(0 0 10px rgba(168,85,247,1))' }}/>`,
`                        <text x={liveDotX + 8} y={liveDotY - 7}`,
`                          fill="#a855f7" fontSize="7" fontWeight="bold" fontFamily="monospace">`,
`                          LIVE`,
`                          <animate attributeName="opacity" values="1;0.25;1" dur="2s" repeatCount="indefinite"/>`,
`                        </text>`,
`                      </g>`,
`                    )}`,
`                  </svg>`,
`                </div>`,
`                {/* 호버 점수 패널 */}`,
`                <div className="absolute right-0 top-0 rounded-xl border transition-all duration-150 overflow-hidden z-10"`,
`                  style={{`,
`                    width:'112px',`,
`                    opacity: graphPos !== null ? 1 : 0,`,
`                    transform: graphPos !== null ? 'translateX(0)' : 'translateX(6px)',`,
`                    pointerEvents:'none',`,
`                    background:'#131325',`,
`                    borderColor:'rgba(255,255,255,0.10)',`,
`                    padding:'8px 10px',`,
`                  }}>`,
`                  <div className="text-white/35 text-[9px] font-mono font-semibold mb-2 tracking-wide">`,
`                    {hoverTime || '──:──:──'}`,
`                  </div>`,
`                  <div className="space-y-1.5">`,
`                    <div className="flex items-center justify-between">`,
`                      <span className="text-white/40 text-[9px]">채팅 반응</span>`,
`                      <span className="text-cyan-400 text-[10px] font-bold">{hoverChat}<span className="text-white/25 text-[8px] font-normal">/80</span></span>`,
`                    </div>`,
`                    <div className="h-0.5 bg-white/[0.07] rounded-full overflow-hidden">`,
`                      <div className="h-full bg-cyan-400/55 rounded-full transition-all duration-75" style={{ width:\`\${hoverChat/80*100}%\` }}/>`,
`                    </div>`,
`                    <div className="flex items-center justify-between">`,
`                      <span className="text-white/40 text-[9px]">영상 분석</span>`,
`                      <span className="text-purple-300 text-[10px] font-bold">{hoverVid}<span className="text-white/25 text-[8px] font-normal">/20</span></span>`,
`                    </div>`,
`                    <div className="h-0.5 bg-white/[0.07] rounded-full overflow-hidden">`,
`                      <div className="h-full bg-purple-400/55 rounded-full transition-all duration-75" style={{ width:\`\${hoverVid*5}%\` }}/>`,
`                    </div>`,
`                  </div>`,
`                  <div className="mt-2 pt-1.5 border-t border-white/[0.07] flex items-center justify-between">`,
`                    <span className="text-white/45 text-[9px]">종합</span>`,
`                    <span className="text-accent-purple text-[12px] font-bold">`,
`                      {hoverTotal}<span className="text-white/25 text-[9px] font-normal">/100</span>`,
`                    </span>`,
`                  </div>`,
`                </div>`,
`              </div>`,
`              <div className="flex mt-1">`,
`                <div style={{width:'22px',flexShrink:0}}/>`,
`                <div className="flex flex-1 justify-between text-[10px] text-white/25">`,
`                  {['00:00:00','01:45:00','03:30:00','05:15:00'].map(t => <span key={t}>{t}</span>)}`,
`                  <span className="inline-flex items-center gap-0.5 text-accent-purple/70">`,
`                    <span className="w-1 h-1 rounded-full bg-accent-purple/80 animate-pulse flex-shrink-0"/>LIVE`,
`                  </span>`,
`                </div>`,
`              </div>`,
`            </div>`,
];
lines.splice(1113, 118, ...wave);

// ── Patch 2: clip thumbnails (above patch3, unaffected by it)
// 1-indexed 1053~1077, 0-indexed 1052~1076, 25 lines
const clips = [
`            {/* 클립 마커 (썬네일) */}`,
`            <div className="flex">`,
`              <div style={{width:'22px',flexShrink:0}}/>`,
`              <div className="relative flex-1" style={{height:'38px'}}>`,
`                {detectedClips.map(clip => {`,
`                  const isSel = selectedLogClip?.rank === clip.rank`,
`                  const isHov = hoveredClip === clip.rank`,
`                  return (`,
`                    <button key={clip.rank}`,
`                      className="absolute bottom-0 flex flex-col items-center gap-0.5"`,
`                      style={{left:\`\${clip.pos}%\`, transform:'translateX(-50%)'}}`,
`                      onClick={() => { setSelectedLogClip(prev => prev?.rank === clip.rank ? null : clip) }}`,
`                      onMouseEnter={() => setHoveredClip(clip.rank)}`,
`                      onMouseLeave={() => setHoveredClip(null)}`,
`                    >`,
`                      <div className={\`rounded overflow-hidden border transition-all \${`,
`                        isSel ? 'border-accent-purple shadow-lg shadow-accent-purple/40 scale-110' :`,
`                        isHov ? 'border-accent-purple/50' : 'border-white/20'`,
`                      }\`} style={{width:'32px',height:'20px'}}>`,
`                        <img src={THUMB_IMGS[(clip.rank-1)%THUMB_IMGS.length]} alt="" className="w-full h-full object-cover"/>`,
`                      </div>`,
`                      <span className={\`text-[7px] font-bold leading-none transition-colors \${`,
`                        isSel ? 'text-accent-purple' : isHov ? 'text-white/65' : 'text-white/30'`,
`                      }\`}>#{clip.rank}</span>`,
`                    </button>`,
`                  )`,
`                })}`,
`              </div>`,
`            </div>`,
];
lines.splice(1052, 25, ...clips);

// ── Patch 1: segment labels
// 1-indexed 1040~1051, 0-indexed 1039~1050, 12 lines
const segs = [
`            <div className="flex">`,
`              <div style={{width:'22px',flexShrink:0}}/>`,
`              <div className="relative h-5 flex-1">`,
`                {BROADCAST_SEGS.map((seg, si) => {`,
`                  if (seg.l >= progress) return null`,
`                  const visW = Math.min(seg.l + seg.w, progress) - seg.l`,
`                  return (`,
`                    <div key={si} className="absolute top-0 bottom-0 rounded-sm px-1 flex items-center overflow-hidden"`,
`                      style={{left:\`\${seg.l}%\`, width:\`\${visW}%\`, background:seg.color}}>`,
`                      <span className="text-[7.5px] font-semibold text-white/90 truncate leading-none">{seg.label}</span>`,
`                    </div>`,
`                  )`,
`                })}`,
`              </div>`,
`            </div>`,
];
lines.splice(1039, 12, ...segs);

fs.writeFileSync(file, lines.join('\n'), 'utf8');
console.log('Done. New total lines:', lines.length);
